### ISSUE TITLE
User can view the list of crypto stocks from the market.

### ISSUE THREAD

**Issue by Michael-M-Aguilar** [Michael-M-Aguilar/ajax-project#1]
## ⚙️ Feature
The user will be able to see a list of the most popular crypto's on the market. 

## 📐 Functionality

A list of the 7 most popular stocks in the crypto market, while pulling from a local crypto API. 

## ✅ Task List
HTML
- [x] Create a div with a container class.
- [x] Create the header of the website page name. 
- [x] Insert both images of WSB and Doge at the top of the page.
- [x] Create a table element
    - [x] Create a thead element for the row of, "Rank, Name, Price, etc".
    - [x] Add the i element for the "sort" button for any thead elements we plan to sort through.  
    - [x] Add the i element for the "info" button for a later feature.
    - [x] Create tr elements for each row that will be present in the table.
    - [x] Create th elements if they're part of the thead row, otherwise td elements on the other rows.
    - [x] Continue until 9 columns are created, and 8 rows are created.
    - [x] Insert the i element of the "note" for a future feature in the last horizontal column. 
    - [x] For the time being, just fill in the first two row with the current information prior to API pull to have an idea of the 
           HTML/CSS.
    - [x] Create a div class modalContainerOff ahead of time. Will need for a future feature. Sibling to table element. 
    - [x] Create a div class modalContent ahead of time. 
    - [x] Create two buttons within the modal content for the time being. First saying "Cancel", second "Save"
    - [ ] 
- [x] Can begin with the CSS now.
    - [x] Create a media query and (min-width: 768 px). targeting the container class. max-width 900px in layout.css
    - [x] Container itself before the media query, should have a margin of 0 auto, and a max-width of 0 auto in layout.css.
    - [x] Create a ruleset for class ".hidden". to make display: none in layout.css.
    - [x] Make the thead row hidden as one of their classes in the media query.
    - [x] Make the header where it show's the website name, background-color blue. Hexcode: B6E7FF
    - [x] Make the thead row a darker grey background-color,  Hexcode: C4C4C4
    - [x] Make the rest of the table rows a lighter grey background-color. Hexcode: F3F1F1
    - [x] For any text container numerals, make the text style: Coda if possible. 
    - [x] For any text that are letters/words, make the text style: Cardo, or something similar if possible. 
    - [x] Add vertical column lines to help distinguish each column for desktop version.
    - [x] Then help add some spacing, or create a slightly thick line to help "separate" each row. 
    - [x] Let the first button have red background-color: F48D8D.  Second one will have green hexcode: 64EF80h
- [x]  Let's start the JS!
    - [x]  First thing we can do is go to a js file. Declare new XMLHttpRequest() to the var xhr.
    - [x] Set the open method, of xhr object, 2 arguments, 'GET', and the website we're trying to pull from
    - [x] setRequestHeader method, of xhr object. 2 arguments. First 'token', second, 'abc123'.
    - [x] responseType method of xhr object, set to a string json. 
    - [x] addEventListener method of xhr object. 2 arguments. 1) 'load'. 2) ananymous function to log the xhr.response
    - [x] send method of xhr object. 
    - [x] From here, we will organize our xhr response to begin to fill in each cell thru the coin's ID #.
