### ISSUE TITLE
User can create a caption for personal usage

### ISSUE THREAD

**Issue by Michael-M-Aguilar** [Michael-M-Aguilar/ajax-project#2]
## ⚙️ Feature
User can create a caption for personal usage for any crypto in partiicular. 

## 📐 Functionality

The ability to save or delete a note for any of the 7 cryptocurrencies.

## 🖼️ Wireframes
![iPhone-8 Notes](https://user-images.githubusercontent.com/82178046/121248352-3235dc80-c858-11eb-83f7-c1acf04c19a5.png)

![Desktop List Version Notes Taking](https://user-images.githubusercontent.com/82178046/121248332-2ba76500-c858-11eb-96e8-ec275467eb58.png)

## ✅ Task List
- [x] ModalContainer already created for desktop. 
    - [x] Create a label 
    - [x] Create the text area. Make sure both have the same name. 
    - [x] Have the the textarea be fixed, so use the CSS property resize: none 
    - [x] Change the fonts of the Cancel and Save to equate to the figma.
- [x] Create ModalContainer for the Mobile version.
    - [x] Create a modal content class as a child to the container.
    - [x] Create buttons for this Mobile version. Once saying Cancel, another with Save, similar to desktop. 
    - [x] Use the same Color CSS as used in desktop. 
- [x] On the Data.JS file 
    - [x] Create an object literal, assign it to a varaible
    - [x] Within object literal, we'll have noteEntry be one of the properties, and it is an empty array.
    - [x] create a variable2 which will be equilavent to the localStorage.getItem(). 
    - [x] create an if statement where if this created variable is not equal to null, the object created from step 1 will be equal to
           JSON.parse(newly created variable2)
    - [x] Create an window addEventListener, with the 'beforeunload' event, and an anonymos function
    - [x] Within anonymous function we'll have to stringify the variable from step 1, and assign it to a new variable. 
    - [x] localstorage.setItem now with two arguments, the first being the variable name from step 1, second argument being the 
           recently created variable from the stringify.  If issues go on [here](https://lfz-lms.herokuapp.com/code-exercises/Learning-Fuze/curriculum/javascript-local-storage?v=b32ab11dbd674b34f8d8c303e7c87037ac87f332)
- [x] On the main.js file
    - [x] Query the Save button.
    - [x] Target the new query, add event listener it, first argument being for 'click', second being an anonymous function
    - [x] create an If statement where the modal will hide after pressing it. 
    - [x] Test the notes, make sure it saves the note previously written in it.
