### ISSUE TITLE
User will able to differentiate between positive and negative cryptos

### ISSUE THREAD

**Issue by Michael-M-Aguilar** [Michael-M-Aguilar/ajax-project#3]
## ⚙️ Feature
User will be able to differentiate between gains or losses for the 1h/1d/1w price Change on desktop, and 1d price Change for mobile.

## 📐 Functionality

The easy visibility if the crypto is up or down for the day. 

## 🖼️ Wireframes
![Desktop List Version](https://user-images.githubusercontent.com/82178046/122300296-fcc26c00-ceb3-11eb-97e6-26239b5cdcc7.png)
![iPhone 8 List](https://user-images.githubusercontent.com/82178046/122300347-0b108800-ceb4-11eb-8b08-cbde5518572e.png)

## ✅ Task List

- [x] First create a class for losses. Assign it color #ff5964.
- [x] Then create a class for gains. Assign it color #00b424. 
- [x] Then adjust the text and font size accordingly since it will overwrite the previous 'numbers' class. 
- [x] Create an if conditional within the renderElements function, not the coinStat API request one.
- [x] If the priceChange is > than 0 ,give it the gains class.
- [x] If the priceChange is < than 0, give it the losses class.
- [x] Use the .className method to change the classes so.
- [x] After doing so, proceed to do the same for the 1h, 1day, and 1 week for desktop.
- [x] On mobile only do so for the 1d priceChange since it doesn't show the same priceChanges.
