### ISSUE TITLE
User can click on a crypto.

### ISSUE THREAD

**Issue by Michael-M-Aguilar** [Michael-M-Aguilar/ajax-project#4]
## ⚙️ Feature

User can click on a certain cryptocurrency.

## 📐 Functionality

By clicking on a cryptocurrency. it'll show further information about the particular crypto. Like market cap, current volume, price changing etc. 

## 🖼️ Wireframes

![Desktop - When Clicked](https://user-images.githubusercontent.com/82178046/121249085-08c98080-c859-11eb-9af7-372446524c28.png)
![iPhone-8 Clicked Stock](https://user-images.githubusercontent.com/82178046/121249105-0f57f800-c859-11eb-87cf-1a7510cc48d3.png)

## ✅ Task List
- [x] Will work on desktop version first.
- [x] First add a query selector for each individual crypto.
- [x] Create an addevent listener for the click event.
- [x] Console log to make sure the row is being targeted, and not a single TD cell.
- [x] This means, create one single backbone HTML for ONE crypto
- [x] Within the page of the new crypto, most of the previous information will be transferred in from the API.
- [x] New addtl feature to this will be direct links from fontawesome icons like their social media.
- [x] Will attempt to add the notes feature for this new page and let it work with the previous JS logic.
- [x] Will have to create a CSS class in which the main page will hide, and the new stock shows up.
- [x] Will also have to create a button in which it'll return the user to the list of cryptos
- [x] The logic of desktop, will then have to be rolled over to Mobile with the same idea. 
- [x] Create a backbone, then create a DOM tree for it. Append it so in the mobile container of the clicked cryptos 
- [x] Create a Dom Tree which will append to the new container for each "individual crypto". 
- [x] Comment out the one crypto created, and let the DOM tree building work.
