### ISSUE TITLE
User can sort the table.

### ISSUE THREAD

**Issue by Michael-M-Aguilar** [Michael-M-Aguilar/ajax-project#5]
## ⚙️ Feature

User can sort the table.

## 📐 Functionality

User can sort the table using the sorting icon to see it in the order of ranks, name, price etc.

## ✅ Task List
- [x] Create a property on data.js, to save the XML Request data.
- [x] Create a function to help sort the column that will be sorted. 
- [x] Within the function declare a variable which will act as our "switch", mark it true.
- [x] Create a while loop, for this "switch"
- [x] Turn it to false so that this while loop doesn't run indefinitely.
- [x] declare a variable which will target/querySelect the rows of the table.
- [x] create a for loop starting from 1 to avoid the first row of headers. 
- [x] second conditional should be the rows.length - 1 since we are avoiding the first row as well.
- [x] create a variable which will target the rows element "TD" element.
- [x] create a variable that will target the columns with the "TD" element.
- [x] Create a method/function here to help do the sorting
- [x] If the 1st var > 2nd var to sort accordingly, (similarly to, an a-b function with a sort method.)
- [x] vice versa for descending.
- [x] Start off with the console logging if the target cell/icon can be clicked.
- [x] Once so, querySelect the Icon/cell
- [x] addEventListener ('click', function (event) {})
- [x] Within this code block, insert the functions created to ascend and descend.
